"""empty message

Revision ID: 2433567e4c07
Revises: 322a6666818a
Create Date: 2014-02-26 21:18:42.150297

"""

# revision identifiers, used by Alembic.
revision = '2433567e4c07'
down_revision = '322a6666818a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    ### end Alembic commands ###
