"""empty message

Revision ID: 261e2b4e1b38
Revises: 4b3c84e928de
Create Date: 2014-03-01 17:43:02.964394

"""

# revision identifiers, used by Alembic.
revision = '261e2b4e1b38'
down_revision = '4b3c84e928de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
