"""empty message

Revision ID: 4b3c84e928de
Revises: 553d58554bb8
Create Date: 2014-03-01 17:25:59.286555

"""

# revision identifiers, used by Alembic.
revision = '4b3c84e928de'
down_revision = '553d58554bb8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
